// packages/angular/src/components/button.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'ark-button',
  template: `
    <button [ngClass]="classes">
      <ng-content></ng-content>
    </button>
  `,
})
export class ButtonComponent {
  @Input() variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' = 'primary';
  @Input() class = '';

  get classes() {
    const baseClasses = 'ark-button';
    const variantClasses = {
      primary: 'ark-button-primary',
      secondary: 'ark-button-secondary',
      success: 'ark-button-success',
      danger: 'ark-button-danger',
      warning: 'ark-button-warning',
      info: 'ark-button-info',
    };

    return `${baseClasses} ${variantClasses[this.variant]} ${this.class}`;
  }
}

// packages/svelte/src/components/Button.svelte
<script>
  export let variant = 'primary';
  let className = '';
  export { className as class };

  const baseClasses = 'ark-button';
  const variantClasses = {
    primary: 'ark-button-primary',
    secondary: 'ark-button-secondary',
    success: 'ark-button-success',
    danger: 'ark-button-danger',
    warning: 'ark-button-warning',
    info: 'ark-button-info',
  };
</script>

<button class="{`${baseClasses} ${variantClasses[variant]} ${className}`}" on:click>
  <slot />
</button>
